// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALjCaS9zqrnx03uKR7ila7_GR9NgFfH70',
    appId: '1:441290716212:web:691cbc40084be1797e0661',
    messagingSenderId: '441290716212',
    projectId: 'cine-shelf',
    authDomain: 'cine-shelf.firebaseapp.com',
    storageBucket: 'cine-shelf.firebasestorage.app',
    measurementId: 'G-0Z2VCBNMRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW6tcEm-jNJiMrhgqRmbDMsc_vq1u4xhQ',
    appId: '1:441290716212:android:c0bb9ea49e0041227e0661',
    messagingSenderId: '441290716212',
    projectId: 'cine-shelf',
    storageBucket: 'cine-shelf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD9CPt8ZPjyQ1jRKZqFc3ugBJFYOPihSE',
    appId: '1:441290716212:ios:d12e8f781b1bdb3e7e0661',
    messagingSenderId: '441290716212',
    projectId: 'cine-shelf',
    storageBucket: 'cine-shelf.firebasestorage.app',
    iosBundleId: 'com.example.cineShelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD9CPt8ZPjyQ1jRKZqFc3ugBJFYOPihSE',
    appId: '1:441290716212:ios:d12e8f781b1bdb3e7e0661',
    messagingSenderId: '441290716212',
    projectId: 'cine-shelf',
    storageBucket: 'cine-shelf.firebasestorage.app',
    iosBundleId: 'com.example.cineShelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALjCaS9zqrnx03uKR7ila7_GR9NgFfH70',
    appId: '1:441290716212:web:edd8ef251ae0517a7e0661',
    messagingSenderId: '441290716212',
    projectId: 'cine-shelf',
    authDomain: 'cine-shelf.firebaseapp.com',
    storageBucket: 'cine-shelf.firebasestorage.app',
    measurementId: 'G-ZB7HC0E77D',
  );
}
